version: '3'

services:
  db:
    image: postgres:latest
    container_name: quiz-db
    environment:
      - POSTGRES_DB=quizapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  quiz-app:
    build: .
    container_name: quiz-app
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TelegramBot__Token=7711998131:AAEIRi04JmNoX-X-ptXUjz8HByOlD5ugm8I
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=quizapp;Username=postgres;Password=12345
    depends_on:
      - db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5295/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  nginx:
    image: nginx:alpine
    container_name: quiz-nginx
    restart: unless-stopped
    ports:
      - "5295:5295"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - quiz-app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5295/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 