[build]
builder = "nixpacks"
buildCommand = "dotnet publish -c Release -o out"

[deploy]
startCommand = "dotnet out/QuizTelegramApp.dll"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "5000"
DOTNET_VERSION = "6.0.0"
