[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet QuizTelegramApp.dll"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "5000"
DOTNET_VERSION = "6.0.0"
